apiVersion: v1
kind: Service
metadata:
  name: {{DEPLOYMENT_NAME}}-service
  namespace: {{NAMESPACE}}
spec:
  type: LoadBalancer
  selector:
    app: {{DEPLOYMENT_NAME}}
  ports:
    - port: {{PORT}}
      targetPort: {{PORT}}

